board: ["seeeduino_xiao_ble"]
shield: ["seedCorne_left", "seedCorne_right"]
include:
  - board: seeeduino_xiao_ble
    shield: seedCorne_left
    artifact-name: seedCorne_left

  - board: seeeduino_xiao_ble
    shield: seedCorne_right
    artifact-name: seedCorne_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
