board: ["seeeduino_xiao_ble"]
shield: ["my_keyboard_left", "my_keyboard_right"]
include:
  - board: seeeduino_xiao_ble
    shield: my_keyboard_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: my_keyboard_left

  - board: seeeduino_xiao_ble
    shield: my_keyboard_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: my_keyboard_right
